# Generated by Django 5.0.1 on 2025-10-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot del comprobante de pago SINPE",
                null=True,
                upload_to="payment_proofs/",
                verbose_name="comprobante de pago",
            ),
        ),
    ]
