# Generated by Django 5.0.1 on 2025-10-19 16:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("MERCHANDISE", "Mercancías"), ("FOOD", "Alimentos")],
                        max_length=20,
                        verbose_name="tipo de categoría",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono para UI",
                        max_length=50,
                        verbose_name="icono",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["category_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="imagen"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="orden")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen de producto",
                "verbose_name_plural": "imágenes de productos",
                "ordering": ["product", "order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="descripción"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio en colones costarricenses (CRC)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="stock disponible",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="disponible"),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array de URLs de imágenes (máximo 5)",
                        verbose_name="imágenes",
                    ),
                ),
                ("views_count", models.IntegerField(default=0, verbose_name="vistas")),
                ("sales_count", models.IntegerField(default=0, verbose_name="ventas")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última actualización"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["-created_at"],
            },
        ),
    ]
