# Generated by Django 5.0.1 on 2025-10-19 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "SELLER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller", "-created_at"], name="products_pr_seller__d25fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "-created_at"],
                name="products_pr_categor_546c8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_available", "-created_at"],
                name="products_pr_is_avai_8299d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-sales_count"], name="products_pr_sales_c_6796bf_idx"
            ),
        ),
    ]
