# Generated by Django 5.0.1 on 2025-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_stock",
            field=models.BooleanField(
                default=False,
                help_text="Si se muestra la cantidad de stock disponible a los compradores",
                verbose_name="mostrar stock",
            ),
        ),
    ]
