# Generated by Django 5.0.1 on 2025-10-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_show_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="accepts_cash",
            field=models.BooleanField(
                default=True,
                help_text="Si el vendedor acepta pago en efectivo para este producto",
                verbose_name="acepta efectivo",
            ),
        ),
    ]
