# Generated by Django 5.0.1 on 2025-10-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_accepts_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de latitud GPS del producto",
                max_digits=9,
                null=True,
                verbose_name="latitud",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de longitud GPS del producto",
                max_digits=9,
                null=True,
                verbose_name="longitud",
            ),
        ),
    ]
