# Generated by Django 5.0.1 on 2025-10-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_latitude_product_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="descripción"
            ),
        ),
    ]
