# Generated by Django 5.0.1 on 2025-10-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_make_product_description_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offers_delivery",
            field=models.BooleanField(
                default=False,
                help_text="Si el producto está disponible para entrega a domicilio",
                verbose_name="ofrece entrega",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="offers_pickup",
            field=models.BooleanField(
                default=True,
                help_text="Si el producto está disponible para recogida en punto físico",
                verbose_name="ofrece recogida",
            ),
        ),
    ]
