# Generated by Django 5.0.1 on 2025-10-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_accepts_sinpe"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="stock_non_negative",
        ),
        migrations.RemoveField(
            model_name="product",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="product",
            name="longitude",
        ),
    ]
