# Generated by Django 5.0.1 on 2025-10-19 16:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Calificación de 1 a 5 estrellas",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="calificación",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Comentario opcional sobre la experiencia de compra",
                        max_length=1000,
                        verbose_name="comentario",
                    ),
                ),
                (
                    "product_quality",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="calidad del producto",
                    ),
                ),
                (
                    "seller_communication",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="comunicación del vendedor",
                    ),
                ),
                (
                    "delivery_speed",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rapidez de entrega",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="visible"),
                ),
                (
                    "is_flagged",
                    models.BooleanField(default=False, verbose_name="marcada"),
                ),
                (
                    "flag_reason",
                    models.TextField(blank=True, verbose_name="razón de marcado"),
                ),
                (
                    "seller_response",
                    models.TextField(blank=True, verbose_name="respuesta del vendedor"),
                ),
                (
                    "seller_responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de respuesta"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "reseña",
                "verbose_name_plural": "reseñas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam"),
                            ("INAPPROPRIATE", "Contenido inapropiado"),
                            ("FAKE", "Reseña falsa"),
                            ("OFFENSIVE", "Lenguaje ofensivo"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="razón",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("REVIEWED", "Revisado"),
                            ("RESOLVED", "Resuelto"),
                            ("DISMISSED", "Descartado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="notas del administrador"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de reporte"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de resolución"
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de reseña",
                "verbose_name_plural": "reportes de reseñas",
                "ordering": ["-created_at"],
            },
        ),
    ]
