# Generated by Django 5.0.1 on 2025-10-19 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "BUYER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="seller",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "SELLER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reviews.review",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["seller", "-created_at"], name="reviews_rev_seller__a381ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["buyer", "-created_at"], name="reviews_rev_buyer_i_bdcc39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-rating", "-created_at"], name="reviews_rev_rating_04081b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["is_visible", "-created_at"],
                name="reviews_rev_is_visi_d4dedd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("order",), name="unique_review_per_order"
            ),
        ),
    ]
