# Generated by Django 5.0.1 on 2025-10-19 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentVerificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("LLM", "LLM Automático"),
                            ("MANUAL", "Revisión Manual"),
                        ],
                        max_length=20,
                        verbose_name="método de verificación",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                            ("PENDING", "Pendiente"),
                        ],
                        max_length=20,
                        verbose_name="resultado",
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="detalles")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
            ],
            options={
                "verbose_name": "log de verificación",
                "verbose_name_plural": "logs de verificación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        help_text="Captura de pantalla del comprobante SINPE Móvil",
                        upload_to="receipts/%Y/%m/%d/",
                        verbose_name="comprobante",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("VERIFYING", "Verificando"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                            ("MANUAL_REVIEW", "Revisión manual"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="estado de verificación",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos extraídos del comprobante por el LLM",
                        verbose_name="datos extraídos",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="notas de verificación"),
                ),
                (
                    "verified_by_llm",
                    models.BooleanField(
                        default=False, verbose_name="verificado por LLM"
                    ),
                ),
                (
                    "llm_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nivel de confianza del LLM (0-100%)",
                        max_digits=5,
                        null=True,
                        verbose_name="confianza del LLM",
                    ),
                ),
                (
                    "reviewed_manually",
                    models.BooleanField(
                        default=False, verbose_name="revisado manualmente"
                    ),
                ),
                (
                    "manual_review_notes",
                    models.TextField(
                        blank=True, verbose_name="notas de revisión manual"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de subida"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de verificación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de expiración"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_receipt",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "comprobante de pago",
                "verbose_name_plural": "comprobantes de pago",
                "ordering": ["-created_at"],
            },
        ),
    ]
