# Generated by Django 5.0.1 on 2025-10-19 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentverificationlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentverificationlog",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_logs",
                to="payments.paymentreceipt",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(fields=["order"], name="payments_pa_order_i_eee159_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(
                fields=["verification_status", "-created_at"],
                name="payments_pa_verific_22f888_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(
                fields=["-expires_at"], name="payments_pa_expires_4633e6_idx"
            ),
        ),
    ]
