# Generated by Django 5.0.1 on 2025-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="offers_delivery",
            field=models.BooleanField(
                default=False,
                help_text="Si el vendedor ofrece servicio de entrega a domicilio",
                verbose_name="ofrece entrega",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="offers_pickup",
            field=models.BooleanField(
                default=True,
                help_text="Si el vendedor permite que clientes recojan productos en su ubicación",
                verbose_name="ofrece recogida",
            ),
        ),
    ]
