# Generated by Django 5.0.1 on 2025-10-21 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_sellerprofile_offers_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de latitud GPS",
                max_digits=9,
                null=True,
                verbose_name="latitud",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de longitud GPS",
                max_digits=9,
                null=True,
                verbose_name="longitud",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="sinpe_number",
            field=models.CharField(
                help_text="Número de teléfono para recibir pagos SINPE Móvil",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número SINPE debe estar en formato: '+50612345678' o '12345678'",
                        regex="^(\\+506)?\\d{8}$",
                    )
                ],
                verbose_name="número SINPE Móvil",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Número de teléfono costarricense",
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número debe estar en formato: '+50612345678' o '12345678'",
                        regex="^(\\+506)?\\d{8}$",
                    )
                ],
                verbose_name="teléfono",
            ),
        ),
    ]
