# Generated by Django 5.0.1 on 2025-10-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_sellerprofile_latitude_sellerprofile_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de latitud GPS para ubicación de entrega",
                max_digits=9,
                null=True,
                verbose_name="latitud",
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de longitud GPS para ubicación de entrega",
                max_digits=9,
                null=True,
                verbose_name="longitud",
            ),
        ),
    ]
